name: Unit tests

on:
  workflow_dispatch:
  push:
    branches: [ main ]
    paths-ignore:
      - '.vscode/**'
      - '.github/**'
      - 'README.md'
  pull_request:
    branches: [ main ] 
    paths-ignore:
      - '.vscode/**'
      - '.github/**'
      - 'README.md'
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore CenturyLocalization/CenturyLocalization/CenturyLocalization.csproj
    - name: Build
      run: dotnet build CenturyLocalization/CenturyLocalization/CenturyLocalization.csproj --no-restore
    - name: Test
      run: dotnet test CenturyLocalization/LocalizationTests/LocalizationTests.csproj --no-build --verbosity normal
