name: Nuget

on:
  push:
    branches: [ main ]
    paths-ignore:
      - '.vscode/**'
      - '.github/**'
      - 'README.md'
  pull_request:
    branches: [ main ] 
    paths-ignore:
      - '.vscode/**'
      - '.github/**'
      - 'README.md'
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal
    - name: Build with dotnet
      run: dotnet pack ./CenturyLocalization --output Packages
    - name: Push to Nuget
      run: dotnet nuget push Packages/ -s nuget.org -k ${{ secrets.NUGET_API_KEY }}
